# Generated by Django 4.2.1 on 2023-05-27 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0002_alter_car_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="category",
            field=models.CharField(
                choices=[
                    ("car", "Auto"),
                    ("pickup", "Camioneta"),
                    ("comecial", "Comercial"),
                    ("suv", "SUV"),
                    ("cross", "CrossOver"),
                ],
                max_length=30,
                verbose_name="Categoria",
            ),
        ),
        migrations.CreateModel(
            name="extra_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motor", models.CharField(max_length=20, verbose_name="Motor")),
                (
                    "transmission",
                    models.CharField(max_length=35, verbose_name="Transmision"),
                ),
                (
                    "suspension",
                    models.CharField(max_length=20, verbose_name="Suspension"),
                ),
                ("brakes", models.CharField(max_length=30, verbose_name="Frenos")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creacion"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Edicion"
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_info",
                        to="car.car",
                    ),
                ),
            ],
        ),
    ]
